### ISSUE TITLE
Ability to merge lane counts into sample counts

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/pycroquet#1]
Replicate and extend crisprReadCounts merge-single functionality - i.e. ability to merge counts from multiple lanes.

May also be useful for dual counts.

@keiranmraine

> Is this:
>
> 1. same output format, just a sum of the inputs as the count column (crisprReadCounts I believe)
> 1. a column for each "read-group" plus a total.
> 1. a single column denoting each "read-group" with `|` separation, plus a total
>
> For (2), (3) to be useful then we'd need some way to indicate the source in the header, but a filename is pretty useless, I guess we could add the MD5 of the individual files too.

@vaofford

> Could we split this out? (1) as a default, with (2) optional

(migrated from internal)

**Comment by keiranmraine** [comment]
Single guide output example, only deals with `id` and `count` columns.  Version and command of the individual count columns are included and linked to the relevant column positions.

```
##Count-col-#1: Version: 1.3.0 ; Command: pycroquet dual-guide -g ../library.tsv -q ../sample.cram -o target -w work --sample Plasmid_library_sample -b TinQ -c 8 --chunks 20000000
##Count-col-#2: Version: 1.3.0 ; Command: pycroquet dual-guide -g ../library.tsv -q ../sample.cram -o target -w work --sample Plasmid_library_sample -b TinQ -c 8 --chunks 20000000
#id     1       2       Plasmid_library_sample
CDKN2A_g01__CDKN2B_g01  297     297     594
CDKN2A_g01__CDKN2B_g03  847     847     1694
...
```

@vaofford is this what you expected to see?

**Comment by vaofford** [comment]
@keiranmraine is this following the convention of (2)?

**Comment by keiranmraine** [comment]
Yes, each input file gets it's command/version added as a header and linked to the column number.  I can add the md5 of the input file too if you think it's worth it.

**Comment by vaofford** [comment]
md5 of the original input would be useful if it's not too much trouble.
in general having the ability to see (a) the input file paths it was generated from and (b) the components of the total count in a single file is very useful
is it possible to have the total in the first column so it's always in the same place for each merged file (i.e. irrespective of the number of files that have been merged)?

**Comment by vaofford** [comment]
will this be implementing merging of counts only or will it be regeneration of the stats file also?

**Comment by keiranmraine** [comment]
If we add in the generation of a stats file during this then the input paths will be collected as the command (and I can also add it to the header more easily).  Recalculation of the stats will be via merging of the stats.json files and will rely on them being in a common location to the counts file.

I can move the total column, I'm thinking everyone uses `array[-1]` but I guess that isn't always available.

**Comment by vaofford** [comment]
Please can we have:
(1) id
(2) gene
(3) total count
(4)...(n) component count

Simple reason my end (not the best reason) is that C-SAR expects counts to be in column (3) - makes it easier when we merge sample counts into a count matrix.

**Comment by vaofford** [comment]
We won't be able to merge the entire stats file. Metrics like guides with low or zero counts will need to be recalculated from the merged total count.

**Comment by keiranmraine** [comment]
I'm aware a few values need to recalculated in the stats

Hmm, the dual guide count files don't have a gene column currently only ID and counts, looks like no-one noticed when we were testing that.

**Comment by vaofford** [comment]
Technically we can get the gene by combining the library downstream. But yes, it would be easier to have it in all count files. Same with guide pair and gene pair information in the dual guide counts (standard counts, not classified counts)

**Comment by keiranmraine** [comment]
To make this possible I've had to standardise the dual-guide outputs to match single-guide format (which they should have from the start).  The stats files are all also in line.  More details will be in the PR

**Comment by keiranmraine** [comment]
Completed in 1.5.0
